name: Build AMI

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-ami:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Variables for Database
      env:
        PORT: ${{ secrets.PORT }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USER: ${{ secrets.MYSQL_USER }}
        DB_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        DB_DIALECT: ${{ secrets.DB_DIALECT }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        echo "PORT=$PORT" >> .env
        echo "DB_HOST=$DB_HOST" >> .env
        echo "DB_PORT=$DB_PORT" >> .env
        echo "DB_USER=$DB_USER" >> .env
        echo "DB_PASSWORD=$DB_PASSWORD" >> .env
        echo "DB_DIALECT=$DB_DIALECT" >> .env
        echo "DB_NAME=$DB_NAME" >> .env

    - name: Compress webapp
      run: zip -r webapp.zip .

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Check Versions and Install Dependencies
      run: |
        pwd
        ls -al
        node -v
        npm -v
        npm install
        ls -al

    - name: Run Integration Tests
      run: npm test

    - name: Install Packer
      run: |  
        sudo apt-get install packer

    - name: Packer Install
      run: |
        cd packer
        packer init .    


    - name: Build AMI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_EC2 }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_EC2 }}
      run: packer build ./packer/aws-debian.pkr.hcl