name: 2nd Packer Check Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  packer-status-check:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packer
        run: |
          packer init ./packer/aws-debian.pkr.hcl

      - name: Packer Format
        run: |
         if ! packer fmt -check ./packer/aws-debian.pkr.hcl; then
           echo "Packer format check failed"
           exit 1
         fi

      - name: Packer Validate 
        run: |
           if ! packer validate ./packer/aws-debian.pkr.hcl; then
             echo "Packer validate failed"
             exit 1
           fi