name: web_app
on:
  pull_request:
    branches: [ main ] # Change this to your main branch name if it's different
    
jobs:
  build:
    name: Web_App_CI
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: 'admin'
          MYSQL_DATABASE: 'healthcheckdb'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: healthcheckdb
      MYSQL_DIALECT: mysql

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v16.x # Change to your preferred Node.js version
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: install nodemon
        run: npm install nodemon
      - name: Run Integration Tests
        run: npm test  
